export const DEFAULT = {
  SHOW_HOME_MESSAGE: false,
  HOME_MESSAGE_URL: "",
  SHOW_HEALTH_FACILITY_MESSAGE: false,
};

export const DAYS_HF_STATUS = {
  DAYS_LONG_TIME_ACTIVE: 180,
  DAYS_MEDIUM_TIME_ACTIVE: 30,
};
export const MODULE_NAME = "home";
